Este es el fork creado para la tarea del 7 de julio del curso de git …
paobtorres/curso_git_essentials pull request #33
Opened 2023-07-07 06:10 UTC by C4r10sM0y4

Soy Carlos Moya, esta es mi tarea del curso Git Essentials, mi usuario es C4r10sM0y4

2023-07-13 22:13 UTC, paobtorres requested changes
Carlos, solo tenian que agregar su usuario de github. Tendrias que eliminar el texto adicional de la segunda linea y hacer un nuevo commit

2023-07-18 21:52 UTC, C4r10sM0y4 commented
Hola Pao, buenas tardes, discutiendo con mis compañeros estamos discutiendo
si cada uno debe trabajar el trabajo desde su propia rama y luego se hace
un merge para juntarlo o si todos trabajamos en la rama principal. Gracias

El jue, 13 jul 2023 a las 19:13, Pao ***@***.***>) escribió:

> ***@***.**** requested changes on this pull request.
>
> Carlos, solo tenian que agregar su usuario de github. Tendrias que
> eliminar el texto adicional de la segunda linea y hacer un nuevo commit
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/paobtorres/curso_git_essentials/pull/33#pullrequestreview-1529310367>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BA6FQOSCHDFDBJNCGYVKFVTXQBXKFANCNFSM6AAAAAA2BLP5UM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-18 21:56 UTC, paobtorres commented
Hola Carlos, para hacer la primera parte lo trabajan todos en la rama principal y cada uno va aportando su parte al codigo. Para la segunda parte que seria completar el script de vectores, si lo trabajan en un rama cada uno como dice el practico. Recuerden hacer el repositorio y agregarnos asi nos pueden etiquetar para las dudas o revision

2023-07-18 21:57 UTC, paobtorres approved these changes

2023-07-18 21:57 UTC, merged

2023-07-26 14:36 UTC, C4r10sM0y4 commented
Hola Paobtorres/Curso_git_essentials, no estoy pudiendo hacer entregas a mi
rama de github

El mar, 18 jul 2023 a las 18:57, Pao ***@***.***>) escribió:

> Merged #33 <https://github.com/paobtorres/curso_git_essentials/pull/33>
> into main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/paobtorres/curso_git_essentials/pull/33#event-9855799604>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BA6FQOTURSPN3U7EJO7MIZ3XQ4BERANCNFSM6AAAAAA2BLP5UM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-07-26 14:42 UTC, paobtorres commented
Hola Carlos, que error tenes?

2023-07-29 21:55 UTC, C4r10sM0y4 commented
Hola Pao, no habia visto la respuesta, pero parece que el error se
soluciono sin darme cuenta de que pude haber hecho. Intente entregarlo una
vez más pero ahora si funciono.

El mié, 26 jul 2023 a las 11:43, Pao ***@***.***>) escribió:

> Hola Carlos, que error tenes?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/paobtorres/curso_git_essentials/pull/33#issuecomment-1651953897>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BA6FQOSJIMRZULMC5ZYKSVDXSEUHRANCNFSM6AAAAAA2BLP5UM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>