Este es mi fork creado para la tarea del curso.
paobtorres/curso_git_essentials pull request #34
Opened 2023-07-07 06:15 UTC by AnaIriarteLopez

Soy Ana Iriarte Lopez y esta es mi tarea del curso.

2023-07-13 22:15 UTC, paobtorres requested changes
Ana solo tenian que agregar su usuario de github. Tendrias que modificar el archivo elimando el texto adicional y volver a realizar el commit

2023-07-17 22:53 UTC, AnaIriarteLopez commented
Hola profe! ¿cómo debería hacerlo?

El El jue, 13 de jul. de 2023 a la(s) 19:15, Pao ***@***.***>
escribió:

> ***@***.**** requested changes on this pull request.
>
> Ana solo tenian que agregar su usuario de github. Tendrias que modificar
> el archivo elimando el texto adicional y volver a realizar el commit
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/paobtorres/curso_git_essentials/pull/34#pullrequestreview-1529311836>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BA62ZB4EKJFICRCB6MVWX5TXQBXR7ANCNFSM6AAAAAA2BLUGMQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-17 23:19 UTC, paobtorres commented
Hola Ana, tendrias que modificar el archivo welcome.md el mismo en el que tenes agregadas las lineas. Eliminar la segunda linea luego hacer un commit y un push. 
Sino si llegas a tener inconvenientes tal vez tengas hacer un git pull y vas a ver que en el archivo welcome.md hay otros usuarios agregados y ahi agregas el tuyo (seguido de un git commit + git push). Cualquier cosa me consultas sino podes

2023-07-18 23:07 UTC, paobtorres approved these changes
Perfecto Ana!

2023-07-18 23:08 UTC, merged