Update readme.md
paobtorres/curso_git_essentials pull request #4
Opened 2023-07-01 00:10 UTC by guadalupecuartara

edite el archivo readme

2023-07-01 00:12 UTC, guadalupecuartara commented
asistencia de hoy 
editar un archivo welcome.md or readme.md

2023-07-11 23:16 UTC, paobtorres requested changes
Solo se debe modificar el archivo welcome.md no el archivo readme.md.
Si se te complica realizar la modicacion, se puede cerrar este pull request y que hagas un git reset a un commit previo en tu repositorio local y que vuelvas a realizar el cambio.

2023-07-12 15:33 UTC, guadalupecuartara commented
buenos días profe, ahi edite el archivo readme.md borrando las líneas agregadas

2023-07-12 15:38 UTC, paobtorres approved these changes

2023-07-12 15:39 UTC, paobtorres commented
Excelente guada!

2023-07-12 15:39 UTC, merged