Agregue mi usuario de github
paobtorres/curso_git_essentials pull request #45
Opened 2023-07-13 01:47 UTC by SantiSabio

2023-07-13 22:34 UTC, paobtorres requested changes
Santi quedo un espacio en el usuario que agregaste

2023-07-14 12:21 UTC, SantiSabio commented
correcion del espacio en el usuario

2023-07-14 12:30 UTC, paobtorres approved these changes
Perfecto Santi ahora si!

2023-07-14 12:30 UTC, merged

2023-07-14 12:53 UTC, SantiSabio commented
Genial profe gracias. Realizo una consulta por aca no se si es lo ideal, en la parte teorica el pdf sale con un error y no se puede abrir

2023-07-14 13:13 UTC, paobtorres commented
Gracias por avisarme Santi. En un rato lo vuelvo a subir